import java.util.Random;
import java.util.Scanner;

public class GuessANumber {
    public static Scanner in = new Scanner( System.in );
    static Random random = new Random();
    static int cpuPlayer = random.nextInt( 100 ) + 1;

    public static void guessANumber() {
        System.out.println( "choose to play:" );
        System.out.println( "1 You have 10 guess" );
        System.out.println( "2 Play until you guess the right number" );
        System.out.println( "3 Main menu" );
        int input = in.nextInt();
        if (input == 1)
            tenGuess();
        else if (input==2)
            unliGuess();
        else if (input==3)
            Menu.main(null);
    }

    public static void tenGuess() {
        System.out.println( "Guess the number generated by computer from 1 to 100, you have 10 guess:" );

        int count = 0;
        while (count < 10) {
            int input = in.nextInt();

            if (cpuPlayer == input)
                System.out.println( "Perfect, you have guess the number" );
            else if (cpuPlayer > input)
                System.out.println( "Wrong, the number is higher" );
            else if (cpuPlayer < input)
                System.out.println( "Wrong, the number is lower" );

            count++;
            System.out.println( "You used " + count + " guess" );
            }
            System.out.println( "And you lose, the number is " + cpuPlayer );
    }

    public static void unliGuess(){
        System.out.println( "Guess the number generated by the computer" );
        do {
            int input = in.nextInt();

            if (cpuPlayer == input) {
                System.out.println( "Perfect, you have guess the number" );
                guessANumber();
            }
            else if (input==0) {
                System.out.println( "Loser!" );
                guessANumber();
            }
            else if (cpuPlayer > input)
                System.out.println( "Wrong, the number is higher. Enter another number or Enter 0 to exit" );
            else if (cpuPlayer < input)
                System.out.println( "Wrong, the number is lower. Enter another number or Enter 0 to exit" );

        }while (true);
    }
}
